apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: pulsar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.13.0
        ports:
        - containerPort: 8200
